/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TApplicationException.h"
#import "TProtocolException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TObjective-C.h"
#import "TBase.h"


@protocol Add <NSObject>
- (int32_t) add: (int32_t) num1 num2: (int32_t) num2;  // throws TException
@end

@interface AddClient : NSObject <Add> {
  id <TProtocol> inProtocol;
  id <TProtocol> outProtocol;
}
- (id) initWithProtocol: (id <TProtocol>) protocol;
- (id) initWithInProtocol: (id <TProtocol>) inProtocol outProtocol: (id <TProtocol>) outProtocol;
@end

@interface AddProcessor : NSObject <TProcessor> {
  id <Add> mService;
  NSDictionary * mMethodMap;
}
- (id) initWithAdd: (id <Add>) service;
- (id<Add>) service;
@end

@interface testConstants : NSObject {
}
@end
